### ISSUE TITLE
Does not work for inactive windows

### ISSUE THREAD

**Issue by kermitfrog** [gerritdevriese/kzones#110]
**Describe the bug**
Dragging a window with Meta+LMB should show the overlay or snap it into the zone when released at the edge.
However this only works for the active window.

**To Reproduce**
1. Open 2 Windows
2. Press and Hold Meta (or whatever you have configured as window modifier)
3. Drag the inactive window with LMB 
4. Error: No KZones overlay appearing

I haven't tried it, but the "Focus follows Mouse" setting might probably needs to be turned off to test this.

**Expected behavior**
This should work the same as it does when the window is active

**System information  (please complete the following information):**
 - KZones version: 0.9
 - Plasma version: 6.2.3
 - Wayland

**Comment by gerritdevriese** [comment]
I see two possible fixes for this:

1. Trigger the overlay for all windows instead of the active window; but this could possibly make it difficult to see which zone you are trying to target, as the window will sometimes appear behind other windows in the window stack.

2. Create a config option "Activate windows on move" that marks the window as active as soon as it is moved, causing the window to become active and trigger the overlay like normal. GNOME appears to do this by default. In my opinion KDE should too, or at least have a setting to allow this, but alas.

**Comment by kermitfrog** [comment]
1. I can think of a few solutions to the visibility issue:
  a) temporarily raise the window (without focussing it) for the move duration
  b) make all other windows transparent
  c) show an always-on-top-outline around the moved window
2. Hm.. this feels a bit unintuitive, as it would switch the focus when I'm not expecting it. It's probably not too bad, but I would prefer the other solution.

**Comment by gerritdevriese** [comment]
I made two changes for this:

- Windows now activate the overlay regardless if they're active or not
- An option to make windows transparent while moving (KZones settings > Fade windows while moving)

Can you build the git version and let me know if this solves your issue?

Also for future reference I found the following setting that makes Meta-drag behave like GNOME's:
Plasma Settings > Window Management > Window Behavior > Window Actions > Inner Window, Titlebar and Fame Actions > Left click > Change "Move" to "Activate, raise and move"

**Comment by kermitfrog** [comment]
Tried it - so far it works. Thanks! :)

When running make 2 things happened:
1. I got the message `/bin/sh: 4: disown: not found`. /bin/sh is a link to dash (default on ubuntu-based systems since 2006 AFAIK), which does not know disown.
2. KWin crashed - probably bacause of 1.

**Comment by gerritdevriese** [comment]
Weird, I thought disown was a built-in command, anyway I'll remove it from the makefile as it's not really needed inside scripts, only if you run the command in a terminal.

The KWin crash is probably just because of Wayland, that happens sometimes 🤷

I'll close the issue as the main topic is resolved.
