### ISSUE TITLE
Meta+Mouse does not trigger OSD

### ISSUE THREAD

**Issue by ChickenIQ** [gerritdevriese/kzones#16]
The OSD and all snapping features are not triggered when the window is moved using SUPER + LClick
Basically, this is only triggered when the window is selected which does not happen while using that shortcut.

Steps to reproduce:
1. Launch an app 
2. Launch another one 
3. Try to move the 1st window
The OSD will appear.
4. Try to move the 2nd window using the shortcut above
The OSD will not be triggered.

**Comment by gerritdevriese** [comment]
I can reproduce this, and after some investigation I don't think I will be able to solve this.

This problem occurs because KWin does not give the correct signal (onClientStartUserMovedResized) when moving an inactive window using Super+LClick. Without this signal its impossible for the script to know when to show the OSD.

I have made a bug report, you can follow it here: https://bugs.kde.org/show_bug.cgi?id=460883

**Comment by codeswhite** [comment]
Please try the `test` branch

**Comment by gerritdevriese** [comment]
> 

Bug is not solved yet upstream, so this issue still exists.
