### ISSUE TITLE
Maximize to zone

### ISSUE THREAD

**Issue by melfahn** [gerritdevriese/kzones#39]
Thanks for your effort on this! Would it be possible to add maximized to the zone you're in? It's crazy to me that maximizing still goes to the full width of the monitor. Can't get any traction with a request at fancy zones and thought I'd give this a try. Thanks!

**Comment by gerritdevriese** [comment]
I tried to implement this, but KWin gets extremely glitchy when there is more then one maximized window. Which is understandable, because under normal circumstances that never happens.

Some other things I discovered:
- Maximized windows do not have any borders/shadows, so it looks weird when padding is enabled
- Maximizing to a zone has the side effect to have a more reliable way to restore its window geometries, may be something we can use in the future.

**Comment by gerritdevriese** [comment]
Have taken a look at this again recently, but couldn't find a way to do this.
