### ISSUE TITLE
Kubuntu 23.10 update breaks KZones [solved]

### ISSUE THREAD

**Issue by markmaker** [gerritdevriese/kzones#72]
Thank you for a great project! :+1: 

I know this is an incomplete observation, but maybe it helps other users solve the same problem, and/or it might help the authors ping a package maintainer, or amend the README.MD, etc:

- Kubuntu 23.10 updated one day, and KZones no longer worked (unfortunately don't know when exactly).
- KDE Plasma version is now indicated as 5.27.8 (unfortunately don't know which it was when KZones still worked).
- When I deleted KZones in System Settings/KWin Scripts, then downloaded it again using the built-in Get New Scripts... function, then logged out and back in, it worked again. And it preserved my layout and settings. :sunglasses:
- I observed KZones auto-updating through Discover before, so I guess this could be solved by somehow triggering that auto-update.

_Mark

**Comment by gerritdevriese** [comment]
I think what happened is that you were auto-updated to KZones v0.7 which is incompatible with Plasma 5.27.x, and by removing and reinstalling the script you actually downloaded "KZones for Plasma 5"

There is a warning on the store page to not update if you are still on Plasma 5, but of course the auto updater doesn't look at this 😆

**Comment by markmaker** [comment]
There is no KZones v0.7 available in the Download New Windows Manager Scripts view:

![Download New Windows Manager Scripts](https://github.com/gerritdevriese/kzones/assets/9963310/0a39f877-3d99-4621-9aef-37013bb3e834)

But maybe it was removed after having caused problems?

**Comment by gerritdevriese** [comment]
There are two separate store pages; KZones (https://store.kde.org/p/1909220) and KZones for Plasma 5 (https://store.kde.org/p/2143914) The "Get new" window only shows scripts that are compatible with your version, that's why you only see that one. BUT if you were already subscribed to "KZones" before it was updated to Plasma 6 the script manager keeps it in the list and thinks it is compatible with your system even though the minimum version is set to Plasma 6 on the KDE store and the script manifest.

**Comment by markmaker** [comment]
Okay then it is explained. But users should still have guidance to resolve this. Perhaps in the readme?

**Comment by gerritdevriese** [comment]
I added some extra info to the readme, hopefully everything is clear now.
